name: ci

on:
  push:
    branches: dev

jobs:
  push-image-dev:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/reallink-backend-dev
            ${{ secrets.DOCKERHUB_USERNAME }}/reallink-backend-dev:${{ steps.package-version.outputs.version }}
